# Generated by Django 3.2.5 on 2023-05-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_orderedproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
